#!/bin/sh

bspc config border_width        2
bspc config window_gap          14

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config top_padding 		0
bspc config bottom_padding 		30
bspc config left_padding 		0
bspc config right_padding 		0

bspc config normal_border_color '#8752ba'
bspc config focused_border_color '#d2275a'
# bspc config urgent_border_color '#f92672'

# bspc monitor DP2 -n λ
bspc monitor eDP1 -n ꙮ

# bspc monitor λ -d 6 7 8 9 10
bspc monitor ꙮ -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2 # Why would you want this?
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam follow=no
bspc rule -a "Even More" floating=on
bspc rule -a "Ipsum Writer" floating=on
bspc rule -a feh* floating=on
bspc rule -a telegram-desktop desktop=^10
bspc rule -a Discord desktop=^5
bspc rule -a \*:"URxvtFuzzy" state=floating center=on sticky=on

/home/avery/.config/bspwm/autostart.sh
